# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KeiwAqAFPqEe6B/FAKi6W5fzZ6CR6Solt2e+nBl2GdA+DWjgXdVNF3lbCTxx1GHXIAYCCi9AjWSK+o4hOdv7HVXnZuiIApQF+oBdrPPlxPc6imJCeKO0zILIAiGsNU4CBOGh2RagOZ3/IsgAxFaAlC77ByHFHVrx+PzY8OK7/4CP9FH23Dw/w0yYZa7xezsKyqtXsEOA+Q5pXRrCy7h4lCIcigTb9z/l8GD3BQxYdufWDvc9CvzmVj0kVJP47R/GgusHPP6T7y9EYOjjgLOQf9osYlFiT0EBpMx5FS9vJ8IDZiEkvxXDvxVqych7XfLLwWNspX5aKoGhrRhZIN55PnjC1YiVp+QN0rljmRNTVFfVa8m0IBcBfJPlE+/kBSBeQXlf/hA//CHUq+JpazJJUxQvKm+Bs6Dbl8WIwJfI6QDjM8+y55zUCCzIR9131NdVnGwwcA5u9shPJtW28E3J/pSlIi3x0fo6kXEwlxSsuG0ST5ag74F7aYJobxMQlvGcYmPT1BxhRyWyhmIBgwoWG/a5KL1rt9rI9eVNYV/qOYnQ6Y4u8GXMl6lsR2J3jOrBl6FlxbpmWRe4vl/BkxWD4lVNmHhn68nCGPPW7Yx3ob7qjKTnJ2A3SnPc6RBsWmcIQ7TUW+WGDSt1Rk1O8kJKyej1ekb5uEyFgCl+1V3Cexs="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      conda config --add channels symengine
      conda config --set show_channel_urls true
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe symengine --channel=main
