travis:
  secure:
    BINSTAR_TOKEN: KeiwAqAFPqEe6B/FAKi6W5fzZ6CR6Solt2e+nBl2GdA+DWjgXdVNF3lbCTxx1GHXIAYCCi9AjWSK+o4hOdv7HVXnZuiIApQF+oBdrPPlxPc6imJCeKO0zILIAiGsNU4CBOGh2RagOZ3/IsgAxFaAlC77ByHFHVrx+PzY8OK7/4CP9FH23Dw/w0yYZa7xezsKyqtXsEOA+Q5pXRrCy7h4lCIcigTb9z/l8GD3BQxYdufWDvc9CvzmVj0kVJP47R/GgusHPP6T7y9EYOjjgLOQf9osYlFiT0EBpMx5FS9vJ8IDZiEkvxXDvxVqych7XfLLwWNspX5aKoGhrRhZIN55PnjC1YiVp+QN0rljmRNTVFfVa8m0IBcBfJPlE+/kBSBeQXlf/hA//CHUq+JpazJJUxQvKm+Bs6Dbl8WIwJfI6QDjM8+y55zUCCzIR9131NdVnGwwcA5u9shPJtW28E3J/pSlIi3x0fo6kXEwlxSsuG0ST5ag74F7aYJobxMQlvGcYmPT1BxhRyWyhmIBgwoWG/a5KL1rt9rI9eVNYV/qOYnQ6Y4u8GXMl6lsR2J3jOrBl6FlxbpmWRe4vl/BkxWD4lVNmHhn68nCGPPW7Yx3ob7qjKTnJ2A3SnPc6RBsWmcIQ7TUW+WGDSt1Rk1O8kJKyej1ekb5uEyFgCl+1V3Cexs=
appveyor:
  secure:
    BINSTAR_TOKEN: h/uXIeXkl+Ljsp4hACwgSledt/euo51bmVHF/Xky+0QErkBK+d4RId3ygHe/GIi7
